- name: Create immich Secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: immich-secrets
        namespace: immich
      type: Opaque
      stringData:
        DB_HOSTNAME: "immich-postgres"
        DB_PORT: "5432"
        DB_USERNAME: "postgres"
        DB_PASSWORD: "{{ postgres_password }}"
        DB_DATABASE_NAME: "immich"
        REDIS_HOSTNAME: "immich-redis"
        REDIS_HOST: "immich-redis"
        REDIS_PORT: "6379"
        UPLOAD_LOCATION: "/data"
        IMMICH_MACHINE_LEARNING_ENABLED: "true"
        IMMICH_MACHINE_LEARNING_URL: "http://immich-machine-learning:3003"
        JWT_SECRET: "{{ jwt_secret }}"

- name: Apply immich manifests
  kubernetes.core.k8s:
    state: present
    template: "{{ playbook_dir }}/../k8s/immich/immich.yaml.j2"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

