services:

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    command:
      - '--path.rootfs=/host'
    networks:
      - monitoring-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "8080:8080"

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro

    networks:
      - monitoring-net

  promtail:
    image: grafana/promtail
    container_name: promtail
    restart: unless-stopped

    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /opt/docker/monitoring-collectors/promtail.yml:/etc/promtail/config.yml

    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true