- name: Create minecraft Secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: minecraft-secrets
        namespace: minecraft
      type: Opaque
      stringData:
        RCON_PASSWORD: "{{ rcon_password }}"

- name: Apply minecraft manifests
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/minecraft/minecraft.yaml"
    kubeconfig: /etc/rancher/k3s/k3s.yaml


- name: Reload prometheus config
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../k8s/monitoring/prometheus.yaml"
    kubeconfig: /etc/rancher/k3s/k3s.yaml
