services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - /opt/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/data/monitoring/prometheus:/prometheus
    ports:
      - "127.0.0.1:9090:9090"
    networks:
      - monitoring-net

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    volumes:
      - /srv/data/monitoring/loki:/loki
    ports:
      - "127.0.0.1:3100:3100"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    external: true