- name: Create n8n Secret
  kubernetes.core.k8s:
    state: present
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: n8n-secrets
        namespace: n8n
      type: Opaque
      stringData:
        N8N_HOST: "n8n.{{ domain }}"
        N8N_PORT: "5678"
        N8N_PROTOCOL: "https"
        WEBHOOK_URL: "https://n8n.{{ domain }}/"
        N8N_ENCRYPTION_KEY: "{{ n8n_encryption_key }}"
        N8N_SECURE_COOKIE: "true"
        N8N_USER_FOLDER: "/home/node/.n8n"

- name: Apply n8n manifests
  kubernetes.core.k8s:
    state: present
    template: "{{ playbook_dir }}/../k8s/n8n/n8n.yaml.j2"
    kubeconfig: /etc/rancher/k3s/k3s.yaml

