- name: Check if backup VG already exists
  command: vgs backup-vg
  register: backup_vg_check
  failed_when: false
  changed_when: false

- name: Create backup VG
  lvg:
    vg: backup-vg
    pvs: /dev/sdb1

- name: Check if backup LV exists
  command: lvs --noheadings -o lv_name backup-vg
  register: backup_lv_check
  failed_when: false
  changed_when: false

- name: Create backup LV if missing
  lvol:
    vg: backup-vg
    lv: backup-lv
    size: 100%FREE
  when: "'backup-lv' not in backup_lv_check.stdout"
