# Backup mount
- name: Create backup mount directory exists
  file:
    path: "{{ backup_root }}"
    state: directory

- name: Check if backup LV is already mounted
  command: mount | grep /srv/backup
  register: backup_mount_check
  failed_when: false
  changed_when: false

- name: Mount backup LV if not already mounted
  mount:
    path: /srv/backup
    src: /dev/backup-vg/backup-lv
    fstype: auto
    opts: defaults
    state: mounted
  when: backup_mount_check.stdout == ""

# Docker mount
- name: Create mount point for Docker
  file:
    path: /var/lib/docker
    state: directory

- name: Format Docker LV if needed
  filesystem:
    fstype: ext4
    dev: /dev/ubuntu-vg/docker

- name: Mount Docker LV
  mount:
    path: /var/lib/docker
    src: /dev/ubuntu-vg/docker
    fstype: ext4
    state: mounted

- name: Create mount point for Data
  file:
    path: /srv/data
    state: directory

- name: Format Data LV if needed
  filesystem:
    fstype: ext4
    dev: /dev/ubuntu-vg/data

- name: Mount Data LV
  mount:
    path: /srv/data
    src: /dev/ubuntu-vg/data
    fstype: ext4
    state: mounted
