---
- name: Create Traefik directory
  ansible.builtin.file:
    path: "{{ docker_root }}/traefik"
    state: directory
    mode: '0755'

- name: Create .env for Traefik
  ansible.builtin.copy:
    dest: "{{ docker_root }}/traefik/.env"
    mode: '0600'
    content: |
      # === Traefik ===
      DOMAIN={{ domain }}

- name: Ensure Traefik external network exists
  community.docker.docker_network:
    name: traefik-net
    state: present

- name: Deploy docker-compose.yml
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_root }}/traefik/docker-compose.yml"
    mode: '0644'

- name: Create Traefik data directory
  ansible.builtin.file:
    path: "{{ data_root }}/traefik"
    state: directory
    mode: '0755'

- name: Ensure acme.json exists with permissions
  ansible.builtin.file:
    # KEEP THIS FILE HERE
    path: "{{ data_root }}/traefik/acme.json"
    state: touch
    owner: root
    group: root
    mode: '0600'

- name: Deploy Traefik config
  ansible.builtin.template:
    src: traefik.yml.j2
    dest: "{{ docker_root }}/traefik/traefik.yml"
    mode: '0644'

- name: Start Traefik
  community.docker.docker_compose_v2:
    project_src: "{{ docker_root }}/traefik"
    state: present
