- name: Check if backup VG already exists
  ansible.builtin.command: vgs backup-vg
  register: backup_vg_check
  failed_when: false
  changed_when: false

- name: Create backup VG
  community.general.lvg:
    vg: backup-vg
    pvs: /dev/sda1

- name: Check if backup LV exists
  ansible.builtin.command: lvs --noheadings -o lv_name backup-vg
  register: backup_lv_check
  failed_when: false
  changed_when: false

- name: Create backup LV if missing
  community.general.lvol:
    vg: backup-vg
    lv: backup
    size: 100%FREE
    shrink: false
  when: backup_lv_check.rc != 0
