- name: Create ubuntu-vg volume group
  community.general.lvg:
    vg: ubuntu-vg
    pvs: /dev/nvme0n1p3
  register: vg_created

- name: Create unused LV (reserved for future use)
  community.general.lvol:
    vg: ubuntu-vg
    lv: docker
    size: 50G
    state: present

- name: Create data volume
  community.general.lvol:
    vg: ubuntu-vg
    lv: data
    size: 800G
    state: present