- name: Storage | LVM
  ansible.builtin.import_tasks: lvm.yml

- name: Storage | backup
  ansible.builtin.include_tasks: backup.yml
  tags: [init_backup]

- name: Storage | mounts
  ansible.builtin.import_tasks: mounts.yml
