# Backup mount
- name: Create backup mount directory exists
  ansible.builtin.file:
    path: "{{ backup_root }}"
    state: directory

- name: Check if backup is already mounted
  ansible.builtin.command: mountpoint -q /srv/backup
  register: backup_mounted
  failed_when: false
  changed_when: false

- name: Mount backup if not already mounted
  ansible.posix.mount:
    path: /srv/backup
    src: /dev/mapper/backup--vg-backup
    fstype: ext4  # seulement si tu es sûr du FS, sinon tu peux le retirer
    opts: defaults
    state: mounted
  when: backup_mounted.rc != 0

# -----------------------------
# Reserved LV (unused, 50G available for future use)
# -----------------------------

# -----------------------------
# Data LV et mount safe
# -----------------------------

- name: Ensure Data mount directory exists
  ansible.builtin.file:
    path: /srv/data
    state: directory

- name: Check if Data filesystem exists
  ansible.builtin.command: blkid /dev/ubuntu-vg/data
  register: data_fs
  failed_when: false
  changed_when: false

- name: Format Data LV if no filesystem
  community.general.filesystem:
    fstype: ext4
    dev: /dev/ubuntu-vg/data
  when: data_fs.rc != 0

- name: Check if Data LV already mounted
  ansible.builtin.command: mountpoint -q /srv/data
  register: data_mounted
  failed_when: false
  changed_when: false

- name: Mount Data LV if not mounted
  ansible.posix.mount:
    path: /srv/data
    src: /dev/ubuntu-vg/data
    fstype: ext4
    opts: defaults
    state: mounted
  when: data_mounted.rc != 0
