- name: Homelab
  hosts: localhost
  connection: local
  # Makes ansible run as root
  become: true
  roles:
    - system
    - storage
    - docker
    - traefik
    - immich
    - nextcloud
    - backup