- name: System | timezone
  import_tasks: timezone.yml

- name: System | Base packages
  import_tasks: packages.yml

- name: System | Firewall
  import_tasks: firewall.yml

- name: System | Bashrc
  import_tasks: bashrc.yml

- name: System | Services
  import_tasks: services.yml

- name: System | Swap
  import_tasks: swap.yml
