- name: System | timezone
  ansible.builtin.import_tasks: timezone.yml

- name: System | Base packages
  ansible.builtin.import_tasks: packages.yml

- name: System | Firewall
  ansible.builtin.import_tasks: firewall.yml

- name: System | Bashrc
  ansible.builtin.import_tasks: bashrc.yml

- name: System | Services
  ansible.builtin.import_tasks: services.yml

- name: System | Swap
  ansible.builtin.import_tasks: swap.yml

- name: System | Fail2ban
  ansible.builtin.import_tasks: fail2ban.yml
