- name: Install homelab restore command
  ansible.builtin.copy:
    src: restore-homelab.sh
    dest: /usr/local/bin/restore-homelab
    owner: root
    group: root
    mode: '0700'

- name: Install homelab backup command
  ansible.builtin.copy:
    src: backup-homelab.sh
    dest: /usr/local/bin/backup-homelab
    owner: root
    group: root
    mode: '0700'

- name: Install homelab start command
  ansible.builtin.copy:
    src: start-homelab.sh
    dest: /usr/local/bin/start-homelab
    owner: root
    group: root
    mode: '0755'

- name: Install homelab stop command
  ansible.builtin.copy:
    src: stop-homelab.sh
    dest: /usr/local/bin/stop-homelab
    owner: root
    group: root
    mode: '0755'