- name: Install homelab restore command
  ansible.builtin.template:
    src: restore-homelab.sh
    dest: /usr/local/bin/restore-homelab
    owner: root
    group: root
    mode: '0700'

- name: Install PostgreSQL backup script
  ansible.builtin.copy:
    src: backup_homelab_postgres.sh
    dest: /usr/local/bin/backup-homelab-postgres
    owner: root
    group: root
    mode: '0700'

- name: Install Restic backup script
  ansible.builtin.template:
    src: backup_homelab_restic.sh
    dest: /usr/local/bin/backup-homelab-restic
    owner: root
    group: root
    mode: '0700'

- name: Install homelab start command
  ansible.builtin.copy:
    src: start-homelab.sh
    dest: /usr/local/bin/start-homelab
    owner: root
    group: root
    mode: '0755'

- name: Install homelab stop command
  ansible.builtin.copy:
    src: stop-homelab.sh
    dest: /usr/local/bin/stop-homelab
    owner: root
    group: root
    mode: '0755'