- name: Check if swapfile exists
  ansible.builtin.stat:
    path: "{{ swap_file }}"
  register: swapfile_stat

- name: Create swapfile
  ansible.builtin.command: fallocate -l {{ swap_size_mb }}M {{ swap_file }}
  when: not swapfile_stat.stat.exists

- name: Set swapfile permissions
  ansible.builtin.file:
    path: "{{ swap_file }}"
    owner: root
    group: root
    mode: '0600'
  when: not swapfile_stat.stat.exists

- name: Format swapfile
  ansible.builtin.command: mkswap {{ swap_file }}
  when: not swapfile_stat.stat.exists

- name: Enable swapfile
  ansible.builtin.command: swapon {{ swap_file }}
  when: not swapfile_stat.stat.exists

- name: Persist swap in fstab
  ansible.posix.mount:
    name: none
    src: "{{ swap_file }}"
    fstype: swap
    opts: sw
    state: present
