{
 "title": "Homelab Monitoring 2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(container_tasks_state,container_label_com_docker_compose_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$service",
   "type": "stat",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "repeat": "service",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_start_time_seconds{\r\n  container_label_com_docker_compose_service=\"$service\"\r\n}",
     "legendFormat": "Uptime"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Estimated Total Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "w" } },
   "targets": [
    {
     "expr": "18 \r\n+ (25 * avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m])))\r\n+ (3 * clamp_max(avg(rate(node_disk_io_time_seconds_total{device=\"sda\"}[1m])), 1))\r\n+ (2.5 * clamp_max(avg(rate(node_disk_io_time_seconds_total{device=\"nvme0n1\"}[1m])), 1))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  { "title": "Docker Services Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  { "title": "Disks status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "NVMe Usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  node_filesystem_size_bytes{device=~\"/dev/mapper/ubuntu--vg.*\", fstype=\"ext4\"}\r\n  - node_filesystem_avail_bytes{device=~\"/dev/mapper/ubuntu--vg.*\", fstype=\"ext4\"}\r\n)",
     "legendFormat": "Used NVME"
    },
    {
     "expr": "sum(\r\n  node_filesystem_avail_bytes{device=~\"/dev/mapper/ubuntu--vg.*\", fstype=\"ext4\"}\r\n)",
     "legendFormat": "Free NVME"
    }
   ]
  },
  {
   "title": "Data LV",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint='/srv/data'} - node_filesystem_avail_bytes{mountpoint='/srv/data'}",
     "legendFormat": "Used Data"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/srv/data'}",
     "legendFormat": "Free Data"
    }
   ]
  },
  {
   "title": "Ubuntu LV",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint='/'} - node_filesystem_avail_bytes{mountpoint='/'}",
     "legendFormat": "Used /"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/'}",
     "legendFormat": "Free /"
    }
   ]
  },
  {
   "title": "System IO",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 21 },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"nvme0n1\"}[1m])",
     "legendFormat": "NVME reads"
    },
    {
     "expr": "-rate(node_disk_writes_completed_total{device=\"nvme0n1\"}[1m])",
     "legendFormat": "NVME writes"
    },
    {
     "expr": "rate(node_disk_reads_completed_total{device=\"sda\"}[1m])",
     "legendFormat": "Backup reads"
    },
    {
     "expr": "-rate(node_disk_writes_completed_total{device=\"sda\"}[1m])",
     "legendFormat": "Backup writes"
    }
   ]
  },
  {
   "title": "HDD Usage",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint='/srv/backup'} - node_filesystem_avail_bytes{mountpoint='/srv/backup'}",
     "legendFormat": "Used HDD"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/srv/backup'}",
     "legendFormat": "Free HDD"
    }
   ]
  },
  {
   "title": "Docker LV",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint='/var/lib/docker'} - node_filesystem_avail_bytes{mountpoint='/var/lib/docker'}",
     "legendFormat": "Used Docker"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/var/lib/docker'}",
     "legendFormat": "Free Docker"
    }
   ]
  },
  {
   "title": "Backup LV",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 9, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint='/srv/backup'} - node_filesystem_avail_bytes{mountpoint='/srv/backup'}",
     "legendFormat": "Used Backup"
    },
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/srv/backup'}",
     "legendFormat": "Free Backup"
    }
   ]
  }
 ]
}