- name: Create Immich directory
  file:
    path: "{{ docker_root }}/immich"
    state: directory
    mode: '0755'

- name: Create .env for Immich
  copy:
    dest: "{{ docker_root}}/immich/.env"
    content: |
      # === Immich ===
      IMMICH_VERSION=release

      # === Database ===
      DB_HOSTNAME=immich-postgres
      DB_PORT=5432
      DB_USERNAME=postgres
      DB_PASSWORD={{ postgres_password }}
      DB_DATABASE_NAME=immich
      DB_DATA_LOCATION=/srv/data/postgres/immich

      # === Redis ===
      REDIS_HOST=redis
      REDIS_PORT=6379

      # === Upload ===
      UPLOAD_LOCATION=/srv/data/immich

      # === Machine learning (CPU only) ===
      IMMICH_MACHINE_LEARNING_ENABLED=true
      IMMICH_MACHINE_LEARNING_URL=http://immich-machine-learning:3003

      # === Sécurité ===
      JWT_SECRET={{ jwt_secret }}

      # === Domaine ===
      DOMAIN={{ domain }}
      EMAIL={{ email }}

      IMMICH_SERVER_URL=https://immich.{{ domain }}
      IMMICH_WEB_URL=https://immich.{{ domain }}

- name: Ensure Immich internal network
  docker_network:
    name: immich-net
    driver: bridge
    state: present

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_root }}/immich/docker-compose.yml"
    mode: '0644'

- name: Start Immich
  community.docker.docker_compose_v2:
    project_src: "{{ docker_root }}/immich"
    state: present