- name: Create docker directory
  file:
    path: "{{ docker_root }}/prometheus"
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0755"

- name: Create data directory
  file:
    path: /srv/data/monitoring/prometheus
    state: directory
    mode: "0755"

- name: Create data directory for loki
  file:
    path: /srv/data/monitoring/loki
    state: directory
    owner: "10001"
    group: "10001"
    mode: "0755"

- name: Copy docker compose
  copy:
    src: docker-compose.yml
    dest: "{{ docker_root }}/prometheus/docker-compose.yml"

- name: Generate prometheus config
  template:
    src: prometheus.yml.j2
    dest: "{{ docker_root }}/prometheus/prometheus.yml"

- name: Start prometheus stack (using Docker Compose CLI v2)
  shell: docker compose up -d
  args:
    chdir: "{{ docker_root }}/prometheus"