- name: Create docker directory
  ansible.builtin.file:
    path: "{{ docker_root }}/prometheus"
    state: directory
    owner: "65534"
    group: "65534"
    mode: "0755"

- name: Create data directory
  ansible.builtin.file:
    path: /srv/data/monitoring/prometheus
    state: directory
    mode: "0755"

- name: Create data directory for loki
  ansible.builtin.file:
    path: /srv/data/monitoring/loki
    state: directory
    owner: "10001"
    group: "10001"
    mode: "0755"

- name: Copy docker compose
  ansible.builtin.copy:
    src: docker-compose.yml
    dest: "{{ docker_root }}/prometheus/docker-compose.yml"

- name: Generate prometheus config
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: "{{ docker_root }}/prometheus/prometheus.yml"

- name: Start prometheus stack
  community.docker.docker_compose_v2:
    project_src: "{{ docker_root }}/prometheus"
    state: present