- name: Create Minecraft directory
  file:
    path: "{{ docker_root }}/minecraft"
    state: directory
    mode: '0755'

- name: Create .env for Minecraft
  copy:
    dest: "{{ docker_root }}/minecraft/.env"
    content: |
      # === Minecraft ===
      EULA=TRUE
      MEMORY=4096M
      MOTD=The Family
      ONLINE_MODE=false
      USE_AIKAR_FLAGS=true
      USE_MEOWICE_FLAGS=true
      TZ=Europe/Paris
      DIFFICULTY=2
      SPAWN_PROTECTION=0
      ENABLE_RCON=true
      RCON_PASSWORD={{ rcon_password }}
      RCON_PORT=25575

      # === Minecraft Exporter ===
      RCON_HOST=minecraft-server

      # === Upload ===
      UPLOAD_LOCATION=/srv/data/minecraft

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_root }}/minecraft/docker-compose.yml"
    mode: '0644'

- name: Start Minecraft
  shell: docker compose up -d
  args:
    chdir: "{{ docker_root }}/minecraft"