- name: Homelab
  hosts: localhost
  connection: local
  # Makes ansible run as root
  become: true
  roles:
    - system
    - storage
    - docker
    - k3s
    - k3s_secrets
    - monitoring_collectors
    - prometheus
    - grafana
    - traefik
    - immich
    - nextcloud
    - minecraft
    - n8n
    - backup