- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com | sh
  args:
    creates: /usr/bin/docker

- name: Install docker-compose plugin
  apt:
    name: docker-compose-plugin
    state: present
    update_cache: yes

- name: Enable Docker
  systemd:
    name: docker
    enabled: true
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes