- name: Install base packages
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
      - lsb-release
      - cron
      - fail2ban
      - htop
      - restic
      - rsync
    state: present
    update_cache: true